apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: event-genie-dev

resources:
  - ../../base
  - namespace.yaml
  - patch-ingress.yaml

patches:
  - path: patch-replicas.yaml

commonLabels:
  environment: dev
