apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: event-genie
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - PLACEHOLDER_SUBDOMAIN
      secretName: event-genie-dev-tls
  rules:
    - host: PLACEHOLDER_SUBDOMAIN
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: event-genie
                port:
                  number: 80
