apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml

commonLabels:
  app: event-genie
  managed-by: argocd

images:
  - name: event-genie
    newName: PLACEHOLDER_ECR_URI
    newTag: latest
