apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml

commonLabels:
  app: event-genie
  managed-by: argocd

images:
  - name: event-genie
    newName: 792373136340.dkr.ecr.us-west-2.amazonaws.com/event-genie
    newTag: aff4669-20260124034501
